In [12]:
from pathlib import Path

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 150)

print("Libraries imported successfully!")

Libraries imported successfully!

In [13]:
DATA_DIR = Path("../data/raw")

deliveries = pd.read_csv(DATA_DIR / "deliveries.csv")
matches = pd.read_csv(DATA_DIR / "matches.csv")
points_table = pd.read_csv(DATA_DIR / "points_table.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [15]:
# check size and columns

datasets = {
    "deliveries": deliveries,
    "matches": matches,
    "points_table": points_table
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print("Dataset:", name)
    print("Rows and columns:", df.shape)
    print("Column names:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())

============================================================
Dataset: deliveries
Rows and columns: (26119, 22)
Column names:
['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed']

First 5 rows:

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,TA Boult,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,TA Boult,4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================
Dataset: matches
Rows and columns: (48, 18)
Column names:
['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city', 'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2', 'reserve_umpire', 'match_referee', 'winner', 'winner_runs', 'winner_wickets', 'match_type']

First 5 rows:

,season,team1,team2,date,match_number,venue,city,toss_winner,toss_decision,player_of_match,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,match_type
0,2023/24,England,New Zealand,2023/10/05,1,Narendra Modi Stadium,Ahmedabad,New Zealand,field,R Ravindra,HDPK Dharmasena,Nitin Menon,Sharfuddoula,J Srinath,New Zealand,NaN,9.0,Group
1,2023/24,Pakistan,Netherlands,2023/10/06,2,Rajiv Gandhi International Stadium,Hyderabad,Netherlands,field,Saud Shakeel,AT Holdstock,CM Brown,PR Reiffel,JJ Crowe,Pakistan,81.0,NaN,Group
2,2023/24,Afghanistan,Bangladesh,2023/10/07,3,Himachal Pradesh Cricket Association Stadium,Dharamsala,Bangladesh,field,Mehedi Hasan Miraz,JS Wilson,HDPK Dharmasena,M Erasmus,AJ Pycroft,Bangladesh,NaN,6.0,Group
3,2023/24,South Africa,Sri Lanka,2023/10/07,4,Arun Jaitley Stadium,Delhi,Sri Lanka,field,AK Markram,RK Illingworth,Sharfuddoula,AG Wharf,J Srinath,South Africa,102.0,NaN,Group
4,2023/24,Australia,India,2023/10/08,5,MA Chidambaram Stadium,Chennai,Australia,bat,KL Rahul,CB Gaffaney,RA Kettleborough,AT Holdstock,RB Richardson,India,NaN,6.0,Group

============================================================
Dataset: points_table
Rows and columns: (10, 11)
Column names:
['Ranking', 'Team', 'Matches', 'Won', 'Lost', 'Tie', 'No Results', 'Points', 'Net Run Rate', 'For', 'Against']

First 5 rows:

   Ranking          Team  Matches  Won  Lost  Tie  No Results  Points  Net Run Rate         For     Against
0        1         India        9    9     0    0           0      18         2.570  2523/396.2  1708/450.0
1        2  South Africa        9    7     2    0           0      14         1.261  2685/437.5  2158/443.0
2        3     Australia        9    7     2    0           0      14         0.841  2631/426.5  2349/441.2
3        4   New Zealand        9    5     4    0           0      10         0.743  2315/378.0  2279/423.3
4        5      Pakistan        9    4     5    0           0       8        -0.199  2328/406.2  2385/402.2

In [21]:
# check data types, nulls and duplicated 
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print("Dataset:", name)
    
    print("\nData types:")
    display(df.dtypes.rename("data_type").to_frame())
    
    print("\nMissing values:")
    display(
        df.isnull()
        .sum()
        .rename("missing_count")
        .to_frame()
        .query("missing_count > 0")
        
    )
    print("\nDuplicate rows:", df.duplicated().sum())

============================================================
Dataset: deliveries

Data types:

                       data_type
match_id                   int64
season                    object
start_date                object
venue                     object
innings                    int64
ball                     float64
batting_team              object
bowling_team              object
striker                   object
non_striker               object
bowler                    object
runs_off_bat               int64
extras                     int64
wides                    float64
noballs                  float64
byes                     float64
legbyes                  float64
penalty                  float64
wicket_type               object
player_dismissed          object
other_wicket_type         object
other_player_dismissed    object

Missing values:

                        missing_count
wides                           25454
noballs                         26063
byes                            26081
legbyes                         25926
penalty                         26118
wicket_type                     25390
player_dismissed                25390
other_wicket_type               26118
other_player_dismissed          26118

Duplicate rows: 1

============================================================
Dataset: matches

Data types:

                data_type
season             object
team1              object
team2              object
date               object
match_number        int64
venue              object
city               object
toss_winner        object
toss_decision      object
player_of_match    object
umpire1            object
umpire2            object
reserve_umpire     object
match_referee      object
winner             object
winner_runs       float64
winner_wickets    float64
match_type         object

Missing values:

                missing_count
reserve_umpire              1
winner_runs                24
winner_wickets             24

Duplicate rows: 0

============================================================
Dataset: points_table

Data types:

             data_type
Ranking          int64
Team            object
Matches          int64
Won              int64
Lost             int64
Tie              int64
No Results       int64
Points           int64
Net Run Rate   float64
For             object
Against         object

Missing values:

Empty DataFrame
Columns: [missing_count]
Index: []

Duplicate rows: 0

In [22]:
# Numeric statistics
for name, df in datasets.items():
    print("\Dataset:", name)
    print(df.describe(include="all").T)

\Dataset: deliveries
                          count unique                                       top   freq       mean        std  min   25%   50%   75%   max
match_id                26119.0    NaN                                       NaN    NaN  24.586508  13.996713  1.0  12.0  24.0  37.0  48.0
season                    26119      1                                   2023/24  26119        NaN        NaN  NaN   NaN   NaN   NaN   NaN
start_date                26119     42                                2023-10-10   1210        NaN        NaN  NaN   NaN   NaN   NaN   NaN
venue                     26119     10  MA Chidambaram Stadium, Chepauk, Chennai   2854        NaN        NaN  NaN   NaN   NaN   NaN   NaN
innings                 26119.0    NaN                                       NaN    NaN   1.448869   0.497388  1.0   1.0   1.0   2.0   2.0
ball                    26119.0    NaN                                       NaN    NaN   22.64749  13.742176  0.1  10.6  22.1  34.1  49.9
batting_team              26119     10                                 Australia   3121        NaN        NaN  NaN   NaN   NaN   NaN   NaN
bowling_team              26119     10                                 Australia   3091        NaN        NaN  NaN   NaN   NaN   NaN   NaN
striker                   26119    146                                   V Kohli    866        NaN        NaN  NaN   NaN   NaN   NaN   NaN
non_striker               26119    144                                   V Kohli    859        NaN        NaN  NaN   NaN   NaN   NaN   NaN
bowler                    26119    102                                   A Zampa    585        NaN        NaN  NaN   NaN   NaN   NaN   NaN
runs_off_bat            26119.0    NaN                                       NaN    NaN   0.896933   1.399963  0.0   0.0   0.0   1.0   6.0
extras                  26119.0    NaN                                       NaN    NaN   0.046403   0.293624  0.0   0.0   0.0   0.0   5.0
wides                     665.0    NaN                                       NaN    NaN   1.218045   0.853222  1.0   1.0   1.0   1.0   5.0
noballs                    56.0    NaN                                       NaN    NaN        1.0        0.0  1.0   1.0   1.0   1.0   1.0
byes                       38.0    NaN                                       NaN    NaN   2.342105   1.475499  1.0   1.0   1.0   4.0   4.0
legbyes                   193.0    NaN                                       NaN    NaN   1.305699   0.850746  1.0   1.0   1.0   1.0   4.0
penalty                     1.0    NaN                                       NaN    NaN        5.0        NaN  5.0   5.0   5.0   5.0   5.0
wicket_type                 729      7                                    caught    448        NaN        NaN  NaN   NaN   NaN   NaN   NaN
player_dismissed            729    140                                 RG Sharma     11        NaN        NaN  NaN   NaN   NaN   NaN   NaN
other_wicket_type             1      1                                 timed out      1        NaN        NaN  NaN   NaN   NaN   NaN   NaN
other_player_dismissed        1      1                                AD Mathews      1        NaN        NaN  NaN   NaN   NaN   NaN   NaN
\Dataset: matches
                count unique                    top freq        mean        std  min    25%    50%    75%    max
season             48      1                2023/24   48         NaN        NaN  NaN    NaN    NaN    NaN    NaN
team1              48     10                  India    6         NaN        NaN  NaN    NaN    NaN    NaN    NaN
team2              48     10            New Zealand    6         NaN        NaN  NaN    NaN    NaN    NaN    NaN
date               48     42             2023/10/10    2         NaN        NaN  NaN    NaN    NaN    NaN    NaN
match_number     48.0    NaN                    NaN  NaN        24.5       14.0  1.0  12.75   24.5  36.25   48.0
venue              48     10  Narendra Modi Stadium    5         NaN        NaN  NaN    NaN    NaN    NaN    NaN
city               48     10              Ahmedabad    5         NaN        NaN  NaN    NaN    NaN    NaN    NaN
toss_winner        48     10                England    7         NaN        NaN  NaN    NaN    NaN    NaN    NaN
toss_decision      48      2                  field   26         NaN        NaN  NaN    NaN    NaN    NaN    NaN
player_of_match    48     37         Mohammed Shami    3         NaN        NaN  NaN    NaN    NaN    NaN    NaN
umpire1            48     14           AT Holdstock    6         NaN        NaN  NaN    NaN    NaN    NaN    NaN
umpire2            48     13       RA Kettleborough    7         NaN        NaN  NaN    NaN    NaN    NaN    NaN
reserve_umpire     47     19            CB Gaffaney    5         NaN        NaN  NaN    NaN    NaN    NaN    NaN
match_referee      48      4             AJ Pycroft   14         NaN        NaN  NaN    NaN    NaN    NaN    NaN
winner             48     10                  India   10         NaN        NaN  NaN    NaN    NaN    NaN    NaN
winner_runs      24.0    NaN                    NaN  NaN  125.916667  82.242968  5.0  69.75  101.0  160.0  309.0
winner_wickets   24.0    NaN                    NaN  NaN    5.916667   2.019829  1.0    5.0    6.0   7.25    9.0
match_type         48      3                  Group   45         NaN        NaN  NaN    NaN    NaN    NaN    NaN
\Dataset: points_table
             count unique         top freq    mean       std    min      25%     50%     75%   max
Ranking       10.0    NaN         NaN  NaN     5.5   3.02765    1.0     3.25     5.5    7.75  10.0
Team            10     10       India    1     NaN       NaN    NaN      NaN     NaN     NaN   NaN
Matches       10.0    NaN         NaN  NaN     9.0       0.0    9.0      9.0     9.0     9.0   9.0
Won           10.0    NaN         NaN  NaN     4.5  2.460804    2.0     2.25     4.0     6.5   9.0
Lost          10.0    NaN         NaN  NaN     4.5  2.460804    0.0      2.5     5.0    6.75   7.0
Tie           10.0    NaN         NaN  NaN     0.0       0.0    0.0      0.0     0.0     0.0   0.0
No Results    10.0    NaN         NaN  NaN     0.0       0.0    0.0      0.0     0.0     0.0   0.0
Points        10.0    NaN         NaN  NaN     9.0  4.921608    4.0      4.5     8.0    13.0  18.0
Net Run Rate  10.0    NaN         NaN  NaN -0.0023  1.352353 -1.825 -0.95825 -0.2675  0.8165  2.57
For             10     10  2523/396.2    1     NaN       NaN    NaN      NaN     NaN     NaN   NaN
Against         10     10  1708/450.0    1     NaN       NaN    NaN      NaN     NaN     NaN   NaN

<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\HP\AppData\Local\Temp\ipykernel_24312\1501046879.py:3: SyntaxWarning: invalid escape sequence '\D'
  print("\Dataset:", name)